services:
  mcp-gateway:
    image: hoangtubk/mcp-gateway:lastest
    environment:
      MCP_ENDPOINT: "wss://api.xiaozhi.me/mcp/?token=your_token_here"
      API_BASE_URL: "http://your_api_url_here:port"
      BasicAuthOptions__Username: "your_username_here"
      BasicAuthOptions__Password: "your_password_here"
    restart: always
